In [1]:
import tensorflow as tf

2022-04-16 19:13:30.391828: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-16 19:13:30.391857: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [37]:

print(tf.__version__)

2.8.0


In [38]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [39]:
scalar.ndim

0

In [40]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [41]:
vector.ndim

1

In [42]:
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [43]:
matrix.ndim

2

In [44]:
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype=tf.float16)

another_matrix                             

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [45]:
another_matrix.ndim

2

In [46]:
tensor = tf.constant([[[1,2,3], 
                       [4,5,6]],
                    [[7,8,9],
                     [10,11,12]],
                    [[13,14,15],
                     [16,17,18]]])

tensor                     

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [47]:
tensor.ndim

3

In [50]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [51]:
changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [52]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [53]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [54]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))


random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [55]:
not_shuffled = tf.constant([[1,2],
                            [3,4],
                            [5,6]]) 
not_shuffled                      

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [62]:
tf.random.set_seed(43)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

In [4]:
tf.ones([10, 7])

2022-04-15 22:50:25.848499: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-04-15 22:50:25.848546: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-04-15 22:50:25.848571: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (localhost): /proc/driver/nvidia/version does not exist
2022-04-15 22:50:25.876035: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [5]:
tf.zeros(shape=(3,4))


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [13]:
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)

X = tf.constant(numpy_A, shape=(3,8))
Y = tf.constant(numpy_A)
X, Y

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

<br>

In [14]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [15]:
rank_4_tensor.ndim

4

In [18]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [19]:
rank_4_tensor.shape, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [20]:
2*3*4*5

120

In [21]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [22]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [23]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [24]:
some_list[:1]

[1]

In [30]:
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
rank_2_tensor = tf.constant([[10,7],
                            [3,4]])
rank_2_tensor                            

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [40]:
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [41]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [42]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [43]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

<br>

In [47]:
tensor = tf.constant([[10,7],[3,4]])

print(tensor+10)
print(tensor-10)
print(tensor*10)
print(tensor/10)
print(tensor//10)

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 0 -3]
 [-7 -6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1.  0.7]
 [0.3 0.4]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[1 0]
 [0 0]], shape=(2, 2), dtype=int32)


In [48]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

## matrix multiplication

In [49]:
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [50]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [51]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [52]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

## CHANGING THE DATA TYPE OF TENSOR

In [2]:
B=tf.constant([1.7, 7.4])
B.dtype

2022-04-16 09:38:11.204364: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-04-16 09:38:11.204399: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-04-16 09:38:11.204419: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (localhost): /proc/driver/nvidia/version does not exist
2022-04-16 09:38:11.231925: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


tf.float32

In [3]:
C= tf.constant([7,10])
C.dtype

tf.int32

In [7]:
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [8]:
E= tf.cast(C, dtype=tf.int16)
E

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([ 7, 10], dtype=int16)>

## Aggregatin tensor

In [9]:
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [10]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

<br>

In [12]:
import numpy as np

In [19]:
E = tf.constant(np.random.randint(0, 100, size=50)) 
E 

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([10, 80, 76, 11, 19, 67, 56, 26, 71, 82, 84, 96,  4, 18, 82, 26, 72,
       10, 64, 34, 36, 23,  5, 25, 47, 82, 47, 32, 59, 96, 50, 15,  1,  9,
       97, 37, 42, 26, 61, 38, 14, 94, 57, 48, 31, 51, 39, 12, 55, 99])>

In [20]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [21]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [22]:
np.min(E)

1

In [23]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [24]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=46>

In [25]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2316>

In [34]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=28.72>

## Find the positional maximum and minimum

In [35]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [36]:
tf.argmax(F) #max position

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [38]:
F[tf.argmax(F)] #max number

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [39]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [40]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [41]:
tf.argmin(F) #min position

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [43]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [44]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

## Squeezing a tensor

In [45]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [46]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [47]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

## one hot encoding

In [56]:
some_list = [0,1,2,3]

tf.one_hot(some_list, depth=3)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)>

In [50]:
tf.one_hot(some_list, depth=4, on_value='Deep learning', off_value='Kya kar rheho yar')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Deep learning', b'Kya kar rheho yar', b'Kya kar rheho yar',
        b'Kya kar rheho yar'],
       [b'Kya kar rheho yar', b'Deep learning', b'Kya kar rheho yar',
        b'Kya kar rheho yar'],
       [b'Kya kar rheho yar', b'Kya kar rheho yar', b'Deep learning',
        b'Kya kar rheho yar'],
       [b'Kya kar rheho yar', b'Kya kar rheho yar', b'Kya kar rheho yar',
        b'Deep learning']], dtype=object)>

## Squaring, log, square root

In [57]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [59]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [61]:
tf.sqrt(H)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt]

In [62]:
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [64]:
tf.math.log(H)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Log}}; Op<name=Log; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Log]

In [65]:
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

In [3]:
import numpy as np

In [5]:
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [6]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [7]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [9]:
# J=tf.constant([3.])
# J.numpy()[0]

In [10]:
numpy_J = tf.constant(np.array([[3.,7.,10.]]))
tensor_J = tf.constant([[3.,7.,10.]])

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [11]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

<br>

## Exercises

In [20]:
#vector
A = tf.constant([1.])
print(A)
print(A.dtype)
print(A.ndim)

tf.Tensor([1.], shape=(1,), dtype=float32)
<dtype: 'float32'>
1


In [22]:
#scalar
B = tf.constant([1., 2., 3.])
print(B)
print(B.dtype)
print(B.ndim)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
<dtype: 'float32'>
1


In [23]:
#matrix
C = tf.constant([[1., 2., 3.],
                [4., 5., 6.],
                [7., 8., 9.],])
print(C)
print(C.dtype)
print(C.ndim)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float32)
<dtype: 'float32'>
2


In [36]:
D = tf.constant([[[1., 2., 3.],
                    [4., 5., 6.],
                    [7., 8., 9.]],
                [[1., 2., 3.],
                    [4., 5., 6.],
                    [7., 8., 9.]]])
print(D)
print(D.dtype)
print(D.ndim)
print(D.shape)
# print(tf.shape(D))
print(tf.rank(D))
print(tf.size(D))
# print(tf.size(D).numpy())

tf.Tensor(
[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]

 [[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]], shape=(2, 3, 3), dtype=float32)
<dtype: 'float32'>
3
(2, 3, 3)
tf.Tensor(3, shape=(), dtype=int32)
18


In [53]:
tensor_A = tf.random.uniform(shape=[50])
# tensor_A = tf.constant(np.random.randint(1,100), shape=50)
# tensor_A = tf.constant(tf.random.uniform(shape=[50]))
# tensor_A = tf.range(1,100, )
tensor_A

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.0947957 , 0.7270223 , 0.2942177 , 0.87189126, 0.7699928 ,
       0.25206006, 0.41896474, 0.50029945, 0.8103726 , 0.5654137 ,
       0.76743805, 0.1911    , 0.36605716, 0.9275453 , 0.68390596,
       0.27896273, 0.8267919 , 0.52291083, 0.36488044, 0.1926949 ,
       0.2233758 , 0.5823362 , 0.8597326 , 0.54571855, 0.07762933,
       0.23421752, 0.5797465 , 0.7104945 , 0.2820996 , 0.63413846,
       0.7014961 , 0.03722906, 0.36407542, 0.60104406, 0.97166073,
       0.07656848, 0.8530698 , 0.7906333 , 0.44539344, 0.29174626,
       0.3916434 , 0.41998327, 0.8672875 , 0.8554226 , 0.46616518,
       0.06030226, 0.6032119 , 0.44083977, 0.63403153, 0.61429167],
      dtype=float32)>

In [72]:
# onse_tensor = tf.ones(shape=(5,300))
# onse_tensor

# zeros_tensor = tf.zeros(shape=(5, 300))
# zeros_tensor

In [70]:
#tf.matmul(zeros_tensor, onse_tensor) #error 

In [71]:
# tf.tensordot(zeros_tensor, onse_tensor) #error

In [81]:
E = tf.random.uniform(shape=[5, 300])
# E

In [82]:
F = tf.random.uniform(shape=[5,300])
# F

In [84]:
tf.matmul(E,F)  #Matrix size-incompatible error

In [86]:
tf.tensordot(E,F, axes=1)  #Matrix size-incompatible error

InvalidArgumentError: Matrix size-incompatible: In[0]: [5,300], In[1]: [5,300] [Op:MatMul]

In [94]:
G = tf.random.uniform(shape=[224, 224, 3])
print('G', G)

G tf.Tensor(
[[[0.07579601 0.9007503  0.63165164]
  [0.7651433  0.14212406 0.4093821 ]
  [0.33812106 0.31682372 0.40583897]
  ...
  [0.64703906 0.8984151  0.3518163 ]
  [0.83639574 0.33184505 0.9699228 ]
  [0.30465567 0.07811141 0.3080362 ]]

 [[0.00155175 0.21691215 0.7103629 ]
  [0.00925672 0.42448664 0.5871278 ]
  [0.99529064 0.7354411  0.42142165]
  ...
  [0.38161314 0.48685646 0.11500132]
  [0.16469848 0.37743914 0.84922934]
  [0.5186603  0.6239736  0.5715331 ]]

 [[0.73767495 0.60924256 0.8735266 ]
  [0.26688182 0.05826008 0.28413618]
  [0.7365345  0.23189688 0.1503948 ]
  ...
  [0.9925864  0.23181069 0.50249493]
  [0.31126237 0.9226711  0.827065  ]
  [0.12900484 0.3235619  0.9117681 ]]

 ...

 [[0.02209783 0.37233233 0.89342   ]
  [0.00657761 0.8200767  0.10852778]
  [0.0740546  0.980471   0.20703483]
  ...
  [0.7963836  0.8168211  0.9941888 ]
  [0.46103466 0.790436   0.13272071]
  [0.66085553 0.08482254 0.2787696 ]]

 [[0.36721182 0.02584827 0.04745257]
  [0.79000103 0.18968976

In [105]:
# tf.argmax(G) #max position
# tf.reduce_max(G)  #max value
# tf.reduce_min(G)  #min value
print('Max value is =',tf.reduce_max(G).numpy()) 
print('Min value is =',tf.reduce_min(G).numpy()) 

Max value is = 0.9999963
Min value is = 3.33786e-06


In [90]:
H = tf.random.uniform(shape=[224, 224, 3])

In [106]:
print('Max value is =',tf.reduce_max(H).numpy()) 
print('Min value is =',tf.reduce_min(H).numpy()) 

Max value is = 0.9999968
Min value is = 4.0650368e-05


In [107]:
# np.min(H) 

4.0650368e-05

In [113]:
I = tf.random.uniform(shape=[1, 224, 224, 3])
I.shape

TensorShape([1, 224, 224, 3])

In [112]:
squeeze_I = tf.squeeze(I)
squeeze_I.shape

TensorShape([224, 224, 3])

In [116]:
# J = tf.constant(np.random.randint(0, 100, size=10)) 
# J
#or |^|
K = tf.random.uniform(shape=[10], minval=10., maxval=100.)
K

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([30.404959, 50.34419 , 65.314285, 35.403374, 36.350086, 72.76683 ,
       32.692024, 29.905188, 21.034758, 22.763346], dtype=float32)>

In [118]:
tf.argmax(K).numpy()

5

In [121]:
K[tf.argmax(K)].numpy()

72.76683

In [131]:
k= tf.cast(K, dtype=tf.int32)  # allowed values: uint8, int32, int64

In [135]:
tf.one_hot(k, depth=3)

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [136]:
tf.add(J)

TypeError: Missing required positional argument